### ISSUE TITLE
oauth parameter "scopes" instead of "scope"

### ISSUE THREAD

**Issue by mari6274** [fernandezpablo85/scribe-java#550]
request_token method provided by api that i use requires OAuth parameter "scopes" instead of "scope" that is specified in OAuthConstans. Is there any way to add custom name of this parameter?

**Comment by fernandezpablo85** [comment]
you'll have to use a RequestTuner for that. check the sources

**Comment by mari6274** [comment]
Thanks for pointing but now i can't add OAuth parameter to my request in ```tune```method because of exception:
```java.lang.IllegalArgumentException: OAuth parameters must either be 'scope' or start with 'oauth_'```

**Comment by fernandezpablo85** [comment]
oh, yeah... validation is a bit strict for your usecase :(

I'd like to leave the validation there because it catches some common issues. If you can reach the api owners perhaps they can support `scope` (no 's') and be consistent with the OAuth protocol? If not I guess your only chance is forking and removing the validation on your fork.

**Comment by mari6274** [comment]
So I'll have to fork but first i will try to contact with the api provider. I couldn't find info about this parameter in OAuth1.0a documentation. Is really ```scope``` parameter specified there?
